#!/usr/bin/env python3
"""Deploy the MaraTUI web dashboard to Node-RED as its own flow tab.

Builds a "MaraTUI Web" tab from index.html + reducer.js and creates or updates it through the
Node-RED admin API, leaving every other flow untouched:

    mqtt in (mara/#) -> function (reduce + keep state) -> websocket out /ws/mara (broadcast)
    websocket in /ws/mara -> function (snapshot for the new client) -> websocket out
    http in GET /mara -> template (the page) -> http response

Usage: ./deploy.py [--url http://192.168.178.162:1880] [--broker <mqtt-broker config node id>]
       ./deploy.py --dry-run   # print the flow JSON instead of deploying
"""

import argparse
import hashlib
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
TAB_LABEL = "MaraTUI Web"
PAGE_PATH = "/mara"
WS_PATH = "/ws/mara"
TOPIC = "mara/#"

STATE_FUNC = """
const now = Date.now();
const kind = String(msg.topic || "").split("/").pop();
let p = msg.payload;
if (typeof p === "string" && kind !== "cup_counter") {
    try { p = JSON.parse(p); } catch (e) { return null; }
}
const S = flow.get("mara") || maraInitialState();
if (!maraReduce(S, kind, p, now)) return null;
flow.set("mara", S);
return { payload: JSON.stringify({ kind: kind, data: p, ts: now }) };
"""

SNAPSHOT_FUNC = """
if (msg.payload !== "hello") return null;
return {
    _session: msg._session,
    payload: JSON.stringify({ kind: "snapshot", data: flow.get("mara") || null, ts: Date.now() }),
};
"""


def nid(name: str) -> str:
    """Stable 16-hex node id, so redeploys update nodes in place instead of duplicating them."""
    return hashlib.sha1(f"maratui-web/{name}".encode()).hexdigest()[:16]


def api(base: str, method: str, path: str, body=None):
    req = urllib.request.Request(
        base.rstrip("/") + path,
        method=method,
        data=None if body is None else json.dumps(body).encode(),
        headers={"Content-Type": "application/json", "Accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        raw = resp.read()
    return json.loads(raw) if raw else None


def find_broker(flows, wanted):
    brokers = [n for n in flows if n["type"] == "mqtt-broker"]
    if wanted:
        match = [b for b in brokers if b["id"] == wanted]
        if not match:
            sys.exit(f"mqtt-broker config node {wanted} not found")
        return match[0]["id"]
    # Prefer the broker the existing MaraTUI flows already use
    for b in brokers:
        if b.get("name") == "MaraTUI Broker":
            return b["id"]
    sys.exit("No 'MaraTUI Broker' mqtt-broker config node found; pass --broker <id>. Available: "
             + ", ".join(f"{b['id']} ({b.get('name')})" for b in brokers))


def build_flow(broker_id: str) -> dict:
    reducer = (HERE / "reducer.js").read_text()
    page = (HERE / "index.html").read_text()
    if "/*__REDUCER__*/" not in page:
        sys.exit("index.html is missing the /*__REDUCER__*/ placeholder")
    page = page.replace("/*__REDUCER__*/", reducer)

    listener = nid("ws-listener")
    ws_out = nid("ws-out")
    nodes = [
        {"id": nid("comment"), "type": "comment", "name": f"MaraTUI Web-Dashboard → http://<host>:1880{PAGE_PATH}",
         "info": "Generated by maratui/dashboard/deploy.py — edit the files there and redeploy instead of editing here.",
         "x": 250, "y": 40, "wires": []},
        {"id": nid("mqtt-in"), "type": "mqtt in", "name": TOPIC, "topic": TOPIC, "qos": "0",
         "datatype": "utf8", "broker": broker_id, "nl": False, "rap": True, "rh": 0, "inputs": 0,
         "x": 130, "y": 100, "wires": [[nid("state")]]},
        {"id": nid("state"), "type": "function", "name": "Zustand + Broadcast",
         "func": reducer + "\n" + STATE_FUNC, "outputs": 1, "timeout": 0, "noerr": 0,
         "initialize": "", "finalize": "", "libs": [], "x": 360, "y": 100, "wires": [[ws_out]]},
        {"id": nid("ws-in"), "type": "websocket in", "name": WS_PATH, "server": listener, "client": "",
         "x": 130, "y": 160, "wires": [[nid("snapshot")]]},
        {"id": nid("snapshot"), "type": "function", "name": "Snapshot an neuen Client",
         "func": SNAPSHOT_FUNC, "outputs": 1, "timeout": 0, "noerr": 0, "initialize": "",
         "finalize": "", "libs": [], "x": 370, "y": 160, "wires": [[ws_out]]},
        {"id": ws_out, "type": "websocket out", "name": WS_PATH, "server": listener, "client": "",
         "x": 600, "y": 130, "wires": []},
        {"id": nid("http-in"), "type": "http in", "name": f"GET {PAGE_PATH}", "url": PAGE_PATH,
         "method": "get", "upload": False, "swaggerDoc": "", "x": 130, "y": 220, "wires": [[nid("page")]]},
        {"id": nid("page"), "type": "template", "name": "index.html", "field": "payload",
         "fieldType": "msg", "format": "html", "syntax": "plain", "template": page, "output": "str",
         "x": 340, "y": 220, "wires": [[nid("http-out")]]},
        {"id": nid("http-out"), "type": "http response", "name": "", "statusCode": "",
         "headers": {"content-type": "text/html; charset=utf-8", "cache-control": "no-cache"},
         "x": 530, "y": 220, "wires": []},
    ]
    configs = [
        {"id": listener, "type": "websocket-listener", "path": WS_PATH, "wholemsg": "false"},
    ]
    return {"label": TAB_LABEL, "nodes": nodes, "configs": configs}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--url", default="http://192.168.178.162:1880", help="Node-RED base URL")
    ap.add_argument("--broker", help="id of the mqtt-broker config node to subscribe with")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    flows = api(args.url, "GET", "/flows")
    broker = find_broker(flows, args.broker)
    flow = build_flow(broker)
    if args.dry_run:
        print(json.dumps(flow, indent=2))
        return

    existing = [n for n in flows if n["type"] == "tab" and n.get("label") == TAB_LABEL]
    try:
        if existing:
            tab_id = existing[0]["id"]
            api(args.url, "PUT", f"/flow/{tab_id}", dict(flow, id=tab_id))
            print(f"Updated flow '{TAB_LABEL}' ({tab_id})")
        else:
            tab_id = api(args.url, "POST", "/flow", flow)["id"]
            print(f"Created flow '{TAB_LABEL}' ({tab_id})")
    except urllib.error.HTTPError as e:
        sys.exit(f"Node-RED rejected the flow: {e.code} {e.read().decode(errors='replace')}")
    print(f"Dashboard: {args.url.rstrip('/')}{PAGE_PATH}")


if __name__ == "__main__":
    main()
